[colors]
background = '%background'
foreground = '%foreground'
selection-background = '%selection-background'
selection-foreground = '%selection-foreground'
cursor = '%cursor'
black = '%black'
red = '%red'
green = '%green'
yellow = '%yellow'
blue = '%blue'
magenta = '%magenta'
cyan = '%cyan'
white = '%white'
light_black = '%light_black'
light_red = '%light_red'
light_green = '%light_green'
light_yellow = '%light_yellow'
light_blue = '%light_blue'
light_magenta = '%light_magenta'
light_cyan = '%light_cyan'
light_white = '%light_white'
