# config: https://raphamorim.io/rio/docs/documentation/configuration-file
cursor = '▇'
performance = "High"
theme = "tokyonight-storm"

# [fonts]
# family = "FiraCode Nerd Font"

[navigation]
mode = "Plain"

[bindings]
keys = [
    { key = "c", with = "control | shift", action = "Copy" },
    { key = "v", with = "control | shift", action = "Paste" },
    { key = "+", with = "control", action = "IncreaseFontSize" },
    { key = "-", with = "control", action = "DecreaseFontSize" },
]
